### ISSUE TITLE
KeyError when a user joins a channel

### ISSUE THREAD

**Issue by scientrollogy** [worblehat/FredIRC#5]
Traceback indicates that, at times, a user joining a channel while capitalizing the channel name in their /join command will result in the client shutting down due to an unhandled exception.

```
Traceback (most recent call last):
  File "d:\shared\python\bot\lib\site-packages\fredirc\client.py", line 500, in data_received
    self._processor.process(message)
  File "d:\shared\python\bot\lib\site-packages\fredirc\processor.py", line 67, in process
    self._process_join(prefix, params)
  File "d:\shared\python\bot\lib\site-packages\fredirc\processor.py", line 162, in _process_join
    self._state.channels[channel]._add_nicks(nick)
KeyError: '#Channelname'
```

I'm very new to programming and python, so I'm not sure why this is happening. Will changing _channel = params[0]_ to _channel = params[0].lower()_ fix this reliably, or is there something else I should be looking at? If it helps, the FredIRC client's /joins are all lowercase #channels.

**Comment by worblehat** [comment]
Hi @scientrollogy 
sorry for the late response. I did not noticed that you created an issue up until now. Thank you for taking the time to report this bug.

Due to lack of time and motivation I decided to no longer maintain FredIRC so I will mark this repository as "archived" soon. I guess this issue is no longer relevant to you anyway? If it is, please let me now.
